-- MySQL Script generated by MySQL Workbench
-- Wed Oct 16 11:19:14 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema project_BD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema project_BD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `project_BD` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `project_BD` ;

-- -----------------------------------------------------
-- Table `project_BD`.`Ataque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_BD`.`Ataque` (
  `id_ataque` INT NOT NULL AUTO_INCREMENT,
  `nombre_ataque` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `daño` INT NULL DEFAULT NULL,
  `tipo` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `level` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_ataque`))
ENGINE = InnoDB
AUTO_INCREMENT = 29
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `project_BD`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_BD`.`Usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(45) NOT NULL,
  `hora_registro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 57
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `project_BD`.`batalla`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_BD`.`batalla` (
  `id_batalla` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL DEFAULT NULL,
  `id_usuario` INT NOT NULL,
  `posion` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_batalla`),
  INDEX `id_usuario_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `project_BD`.`Usuarios` (`id_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `project_BD`.`Historial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_BD`.`Historial` (
  `id_historial` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL DEFAULT now(),
  `id_batalla` INT NULL DEFAULT NULL,
  `usuario` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `resultado` ENUM('ganador', 'perdedor') CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `tiempo_votacion` DATETIME NULL DEFAULT now(),
  `pokemon_elegido` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id_historial`),
  INDEX `id_batalla_idx` (`id_batalla` ASC) VISIBLE,
  CONSTRAINT `fk_id_batalla`
    FOREIGN KEY (`id_batalla`)
    REFERENCES `project_BD`.`batalla` (`id_batalla`))
ENGINE = InnoDB
AUTO_INCREMENT = 139
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `project_BD`.`pokemon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_BD`.`pokemon` (
  `id_pokemon` INT NOT NULL AUTO_INCREMENT,
  `nombre_pokemon` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `tipo` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `HP` INT NULL DEFAULT NULL,
  `defensa` INT NULL DEFAULT NULL,
  `ataque` INT NULL DEFAULT NULL,
  `speed` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_pokemon`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `project_BD`.`accion_batalla`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_BD`.`accion_batalla` (
  `id_accion` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NULL DEFAULT NULL,
  `id_ataque` INT NULL DEFAULT NULL,
  `id_pokemon` INT NULL DEFAULT NULL,
  `fecha` DATETIME NULL DEFAULT now(),
  PRIMARY KEY (`id_accion`),
  INDEX `id_usuario_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `id_ataque_idx` (`id_ataque` ASC) VISIBLE,
  INDEX `id_pokemon_idx` (`id_pokemon` ASC) VISIBLE,
  CONSTRAINT `fk_id_ataque`
    FOREIGN KEY (`id_ataque`)
    REFERENCES `project_BD`.`Ataque` (`id_ataque`),
  CONSTRAINT `fk_id_pokemon`
    FOREIGN KEY (`id_pokemon`)
    REFERENCES `project_BD`.`pokemon` (`id_pokemon`),
  CONSTRAINT `fk_id_usuario_accion`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `project_BD`.`Usuarios` (`id_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `project_BD`.`pokemon_has_ataque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_BD`.`pokemon_has_ataque` (
  `pokemon_id_pokemon` INT NOT NULL,
  `ataque_id_ataque` INT NOT NULL,
  PRIMARY KEY (`pokemon_id_pokemon`, `ataque_id_ataque`),
  INDEX `fk_ataque` (`ataque_id_ataque` ASC) VISIBLE,
  CONSTRAINT `fk_ataque`
    FOREIGN KEY (`ataque_id_ataque`)
    REFERENCES `project_BD`.`Ataque` (`id_ataque`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pokemon`
    FOREIGN KEY (`pokemon_id_pokemon`)
    REFERENCES `project_BD`.`pokemon` (`id_pokemon`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `project_BD`.`votaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_BD`.`votaciones` (
  `id_votacion` INT NOT NULL AUTO_INCREMENT,
  `tiempo_votacion` DATETIME NULL DEFAULT NULL,
  `id_usuario` INT NOT NULL,
  `id_batalla` INT NOT NULL,
  `pokemon_elegido` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_votacion`),
  INDEX `id_usuario_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `id_batalla_idx` (`id_batalla` ASC) VISIBLE,
  CONSTRAINT `fk_id_batalla_votacion`
    FOREIGN KEY (`id_batalla`)
    REFERENCES `project_BD`.`batalla` (`id_batalla`),
  CONSTRAINT `fk_id_usuario_votacion`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `project_BD`.`Usuarios` (`id_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 45
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
